### ISSUE TITLE
Dont work on Sponge

### ISSUE THREAD

**Issue by BlayzerQ** [JonnyNova/SmartMoving#7]
When i install it on Sponge server, i get this:
http://paste.org.ru/?4one88
`[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$spongeGetScaledHealthForPacket$zfi000(Lnet/minecraft/entity/player/EntityPlayerMP;)F in mixins.common.core.json:entity.player.MixinEntityPlayerMP failed injection check, (0/1) succeeded
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:266)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1114)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:891)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:300)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:259)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:834)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:804)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:609)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.getMethod0(Class.java:3018)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.getMethod(Class.java:1784)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
[02:54:11] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: java.lang.reflect.InvocationTargetException
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayerMP
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getMethod0(Class.java:3018)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getMethod(Class.java:1784)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:54:11] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	... 6 more
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayerMP
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 13 more
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:621)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	... 15 more
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$spongeGetScaledHealthForPacket$zfi000(Lnet/minecraft/entity/player/EntityPlayerMP;)F in mixins.common.core.json:entity.player.MixinEntityPlayerMP failed injection check, (0/1) succeeded
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:266)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1114)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:891)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:300)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:259)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:834)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:804)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:609)
[02:54:11] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 18 more`

**Comment by ProfCupcake** [comment]
Looks like it's another classic case of [Sponge & PlayerAPI incompatibility](https://github.com/SpongePowered/SpongeForge/issues/1659#issuecomment-316169095). 

Nothing can be done here.

**Comment by JonnyNova** [comment]
Thanks for the info ProfCupcake. Closing
